# Generated by Django 6.0.4 on 2026-04-16 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
